### ISSUE TITLE
kingstudy_feature/api-intergrate-change-password

### ISSUE THREAD

**Issue by linhbui-gif** [linhbui-gif/kingstudy-website-v2#109]
1, Đăng nhập với tài khoản
buiquanglinh1408@gmail.com
Duyen@1998
2, Vào trang /profile?page=setting
3, Chọn đổi mật khẩu
4, Validate Field + ghép api ở đây (Lưu ý phải có loading đầy đủ)

**Comment by quocdat16061990** [comment]
https://github.com/linhbui-gif/kingstudy-website-v2/pull/114

Hiện giờ chưa có API nên chỉ làm dc validation .
