### ISSUE TITLE
kingstudy_style-step-container

### ISSUE THREAD

**Issue by linhbui-gif** [linhbui-gif/kingstudy-website-v2#110]
1, Tạo 1 container là Step giống như web myguustore
2, Thay đổi UI sao cho phù hợp với giao diện của kingstudy

**Comment by quocdat16061990** [comment]
https://github.com/linhbui-gif/kingstudy-website-v2/pull/115

Demo : 


![Image](https://github.com/linhbui-gif/kingstudy-website-v2/assets/26184797/bf74d030-3acb-4e6c-a8cf-4602aaf739ab)
